spring:
  datasource:
    url: jdbc:mysql://localhost:3306/center?useUnicode=TRUE&characterEncoding=utf8&autoReconnect=true&serverTimezone=UTC&useSSL=false
    username: root
    password: 1393687715
    driver-class-name: com.mysql.cj.jdbc.Driver

server:
  port: 8888

mybatis:
  mapper-locations: classpath*:mapper/*.xml

logging:
  level:
  com:
    xiaoyi:
      personalweb:
        mapper: debug
