spring:
  datasource:
    url: jdbc:mysql://localhost:3306/xiaoyi?useUnicode=TRUE&characterEncoding=utf8&autoReconnect=true&serverTimezone=UTC&useSSL=false
    username: root
    password: 1393687715
    driver-class-name: com.mysql.cj.jdbc.Driver
  jackson:
    # 格式化全局时间字段
    date-format: yyyy-MM-dd HH:mm:ss
    # 指定时间区域类型
    time-zone: GMT+8

server:
  port: 8888
  servlet:
    context-path: /dev-api

mybatis-plus:
  mapper-locations: classpath*:mybatis/*.xml
  global-config:
    db-config:
      logic-delete-field: delete_status #默认deleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto

logging:
  level:
    com:
      xiaoyi:
        personalweb:
          mapper: debug
